import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html>
      <Head>
        <meta
          content="Meta Pool is a liquid staking solution for NEAR blockchain, earn staking rewards without locking NEAR tokens. Receive stNEAR a liquid token  in return"
          name="description"
        />
        <meta
          content="Meta Pool, Liquid Staking, NEAR, Blockchain, stNEAR, META token, Staking rewards, Liquidity Pool"
          name="keywords"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <link
          href="assets/img/apple-touch-icon.png"
          rel="apple-touch-icon"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
          rel="stylesheet"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
