import type { NextPage } from "next";
import Head from "next/head";
import {
  ChakraProvider,
  theme,
  VStack,
  HStack,
  Center,
  Text,
  Box,
  Image,
  Flex,
} from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <>
      <ChakraProvider theme={theme}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Center
          w="100%"
          bg="white"
          p="17px"
          fontWeight="semibold"
          fontSize="md"
        >
          This is a news update that worth to pay attention and maybe click on
          it
        </Center>
        <VStack
          bg="#F2F2F2"
          bgImage="url('bg-home-main.svg')"
          bgSize="cover"
          bgPosition="center center"
          w="100%"
          spacing="0"
          h="1038px"
        >
          <Flex
            w="100%"
            justifyContent="space-between"
            alignItems="center"
            direction="row"
            py="2rem"
            px="2rem"
            bg="#F2F2F2"
          >
            <Image alt="logo" src={"logo.svg"} w="202" h="34" />
            <Box
              as="button"
              p={4}
              fontWeight="semibold"
              borderRadius="30px"
              bg="transparent"
              border="2px"
              py="14px"
              px="44px"
            >
              <Text fontWeight="normal">Start staking</Text>
            </Box>
          </Flex>

          <Box w="100%" h="100%">
            <Box>
              <Center>
                <Box>
                  Stake NEAR,
                  <br /> maximise returns
                </Box>
              </Center>
              <Center>
                <p>
                  Receive stNEAR to access liquidity without having to sell your
                  assets.
                </p>
              </Center>
              <Center>
                <Box
                  as="button"
                  p={4}
                  color="white"
                  fontWeight="bold"
                  borderRadius="3xl"
                  bg="#0F172A"
                  py="16px"
                  px="46px"
                >
                  <Text fontWeight="normal">Start staking</Text>
                </Box>
              </Center>
            </Box>
          </Box>
        </VStack>
      </ChakraProvider>
    </>
  );
};

export default Home;
