import type { NextPage } from "next";
import Head from "next/head";
import {
  ChakraProvider,
  theme,
  VStack,
  Center,
  Text,
  Box,
  Image,
} from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <>
      <ChakraProvider theme={theme}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <VStack spacing="0">
          <Center w="100%" h="100%" bg="white" p="17px">
            <Text fontWeight="semibold" fontSize="md">
              This is a news update that worth to pay attention and maybe click
              on it
            </Text>
          </Center>
          <Box w="100%" h="100%" bg="#F2F2F2" pos="relative">
            <Box
              zIndex="0"
              pos="absolute"
              w="100%"
              h="100%"
              py="2em"
              px="4em"
              bgGradient="linear(to-r,rgba(255, 180, 40, 0.64), rgba(204, 0, 255, 0.64))"
              blur="200px"
            ></Box>
            <Image alt="logo" src={"logo.svg"} w="202" h="34" />;
            <Box zIndex="1">Stake NEAR, maximise returns</Box>
            <p>
              Receive stNEAR to access liquidity without having to sell your
              assets.
            </p>
            <Box
              as="button"
              p={4}
              color="white"
              fontWeight="bold"
              borderRadius="3xl"
              bg="#0F172A"
              py="16px"
              px="46px"
            >
              <Text fontWeight="normal">Start stanking</Text>
            </Box>
          </Box>
        </VStack>
      </ChakraProvider>
    </>
  );
};

export default Home;
